### ISSUE TITLE
Would it be possible to download multiple videos at once?

### ISSUE THREAD

**Issue by hanatangg** [shataniya/ibili#1]
For an example, I want to download both av12787089 and av26008357
```
const ibili = require("./ibili")
// 使用 视频的av号下载视频
ibili.downloadVideo({
	url:"https://www.bilibili.com/video/av12787089",
	url:"https://www.bilibili.com/video/av26008357"
})
```
Thank you!

**Comment by shataniya** [comment]
url can be an array。
for example：
const ibili = require('ibili')
ibili.downloadVideo({
&nbsp; &nbsp; url: [
&nbsp; &nbsp; &nbsp; &nbsp; 'https://www.bilibili.com/video/av12787089',
&nbsp; &nbsp; &nbsp; &nbsp; 'https://www.bilibili.com/video/av26008357'
&nbsp; &nbsp; ]
}).then(()=&gt;{
&nbsp; &nbsp; console.log('ok')
})





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"hanatangg"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月3日(星期二) 下午4:25
收件人:&nbsp;"shataniya/ibili"<ibili@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[shataniya/ibili] Would it be possible to download multiple videos at once? (#1)




For an example, I want to download both av12787089 and av26008357
 const ibili = require("./ibili") // 使用 视频的av号下载视频 ibili.downloadVideo({ 	url:"https://www.bilibili.com/video/av12787089", 	url:"https://www.bilibili.com/video/av26008357" })  
Thank you!

**Comment by hanatangg** [comment]
It works!
Thank you~!
